# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27562181e57b1def6dd20638ecb89aa1d9abdedb68c2d8e1e7d183e0e4db98b69dd3322d3ca8ca8f24b3bafb79075bfb46ce70c2252c801f0e26298b7132ea7

test:
  secret_key_base: 48339d816b42f4058f588fe261445db848a797c42f8a1433a06310cd03e25093dbbdd5235042a151b1fa1f90bbad726a301b75c5f50a6af467dbc67bd86c68e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
